# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_vb_cam_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, a_bar, b_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_sanba_main_vb_cam_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, a_bar, b_bar, epsilon, maxSIM, verbose)
}

main_vb_cam_CP_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, epsilon, maxSIM, verbose = 0L) {
    .Call(`_sanba_main_vb_cam_CP_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, epsilon, maxSIM, verbose)
}

main_vb_fSAN_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, alpha_bar, beta_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_sanba_main_vb_fSAN_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, alpha_bar, beta_bar, epsilon, maxSIM, verbose)
}

main_vb_fiSAN_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, beta_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_sanba_main_vb_fiSAN_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, beta_bar, epsilon, maxSIM, verbose)
}

main_vb_fiSAN_CP_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, beta_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_sanba_main_vb_fiSAN_CP_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, beta_bar, epsilon, maxSIM, verbose)
}

sample_CAM_cpp <- function(nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, fixed_alpha, fixed_beta, alpha, beta, hyp_alpha1, hyp_alpha2, hyp_beta1, hyp_beta2, mu_start, sigma2_start, M_start, S_start, alpha_start, beta_start, progressbar) {
    .Call(`_sanba_sample_CAM_cpp`, nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, fixed_alpha, fixed_beta, alpha, beta, hyp_alpha1, hyp_alpha2, hyp_beta1, hyp_beta2, mu_start, sigma2_start, M_start, S_start, alpha_start, beta_start, progressbar)
}

sample_fiSAN_cpp <- function(nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, hyp_alpha1, hyp_alpha2, fixed_alpha, mu_start, sigma2_start, M_start, S_start, progressbar) {
    .Call(`_sanba_sample_fiSAN_cpp`, nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, hyp_alpha1, hyp_alpha2, fixed_alpha, mu_start, sigma2_start, M_start, S_start, progressbar)
}

sample_fSAN_cpp <- function(nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, mu_start, sigma2_start, M_start, S_start, progressbar) {
    .Call(`_sanba_sample_fSAN_cpp`, nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, mu_start, sigma2_start, M_start, S_start, progressbar)
}

